#!/usr/bin/env Rscript
# ============================================================
# GABM Mobility Curve — Model 3 POLE-LEVEL Re-fit
#
# Replaces dimension-level mention flags with pole-level flags.
# For each Big Five dimension, each pole is a separate decision:
#   - If positive-pole mention rate in [15%, 85%]:
#       include `mentioned_<pos_pole>` + `<trait>:mentioned_<pos_pole>`
#   - If negative-pole mention rate in [15%, 85%]:
#       include `mentioned_<neg_pole>` + `<trait>:mentioned_<neg_pole>`
#
# Trait dummies (extraverted, agreeable, etc.) are ALWAYS included.
# Uses mention_flags_pole.csv (generated by generate_pole_flags.py).
#
# Patches model3 in each config's JSON with the new fit.
#
# Usage:
#   Rscript analysis/refit_model3_pole.R --only <config> [--threshold 0.15]
#   Rscript analysis/refit_model3_pole.R --cores 4
# ============================================================

library(data.table)
library(lme4)
library(jsonlite)
library(DHARMa)
library(parallel)

args_raw <- commandArgs(trailingOnly = TRUE)
n_cores <- 1L
ix <- which(args_raw == "--cores"); if (length(ix) > 0 && length(args_raw) > ix) n_cores <- max(1L, as.integer(args_raw[ix + 1]))
only_key <- NULL
ix <- which(args_raw == "--only"); if (length(ix) > 0 && length(args_raw) > ix) only_key <- args_raw[ix + 1]
threshold <- 0.15
ix <- which(args_raw == "--threshold"); if (length(ix) > 0 && length(args_raw) > ix) threshold <- as.numeric(args_raw[ix + 1])

cat(sprintf("Threshold: pole mention rate in [%.2f, %.2f] to include\n", threshold, 1 - threshold))
cat(sprintf("Cores: %d\n", n_cores))
if (!is.null(only_key)) cat(sprintf("Only: %s\n", only_key))

script_args <- commandArgs(trailingOnly = FALSE)
script_path <- sub("--file=", "", script_args[grep("--file=", script_args)])
BASE_DIR <- if (length(script_path) == 0) { normalizePath(".") } else { normalizePath(file.path(dirname(script_path), "..")) }
DATA_DIR <- file.path(BASE_DIR, "viz", "data", "real")
OUT_DIR  <- file.path(DATA_DIR, "regressions")
AGENTS_FILE <- file.path(BASE_DIR, "agents", "agents.json")

agents_raw <- fromJSON(AGENTS_FILE)
agents <- data.table(agent_id = agents_raw$agent_id, gender = agents_raw$gender)

json_files <- list.files(OUT_DIR, pattern = "\\.json$", full.names = TRUE)
if (!is.null(only_key)) json_files <- json_files[grepl(only_key, basename(json_files), fixed = TRUE)]
cat(sprintf("Processing %d file(s)\n\n", length(json_files)))

# ── Significance stars + coef extractor ──────────────────────
sig_stars <- function(p) ifelse(p < 0.001, "***", ifelse(p < 0.01, "**", ifelse(p < 0.05, "*", ifelse(p < 0.1, ".", ""))))
extract_coefs <- function(coef_table) {
  result <- list()
  nms <- rownames(coef_table)
  for (i in seq_along(nms)) {
    nm <- nms[i]
    est <- coef_table[i, "Estimate"]; se <- coef_table[i, "Std. Error"]
    z <- coef_table[i, "z value"]; p <- coef_table[i, "Pr(>|z|)"]
    key <- tolower(gsub("[^a-zA-Z0-9]", "_", nm))
    key <- gsub("_+", "_", key); key <- gsub("^_|_$", "", key)
    if (grepl("intercept", key, ignore.case = TRUE)) key <- "intercept"
    if (key == "i_infection_pct_2_" || key == "i_infection_pct_2") key <- "infection_pct_sq"
    result[[key]] <- list(estimate = round(est, 6), se = round(se, 6),
                          z = round(z, 4), p = p, or = exp(est),
                          or_ci_lo = exp(est - 1.96 * se), or_ci_hi = exp(est + 1.96 * se),
                          sig = sig_stars(p))
  }
  result
}

# ── Pole → trait-dummy mapping ────────────────────────────────
# Each pole interacts with the corresponding trait dummy (which codes
# the agent's actual trait, not the mention). Trait dummy matches one pole
# of the dimension — interaction semantics differ by pole:
#   extraverted × mentioned_extroverted  → matching-pole amplification (agent is extra, "extra" mentioned)
#   extraverted × mentioned_introverted  → contrasting-pole (agent is extra, "intro" mentioned)
POLE_TO_TRAIT <- list(
  extroverted      = "extraverted",
  introverted      = "extraverted",
  agreeable        = "agreeable",
  antagonistic     = "agreeable",
  conscientious    = "conscientious",
  unconscientious  = "conscientious",
  neurotic         = "emot_stable",
  emot_stable      = "emot_stable",
  open             = "open_to_exp",
  closed           = "open_to_exp"
)
POLE_NAMES <- names(POLE_TO_TRAIT)
CONTEXT_FLAGS <- list(
  infection = "infection_pct",
  age       = "age_years"
)

process_one <- function(json_path) {
  config_key <- sub("\\.json$", "", basename(json_path))
  micro_file <- file.path(DATA_DIR, config_key, "probe_results_micro.csv")
  flags_file <- file.path(DATA_DIR, config_key, "mention_flags_pole.csv")
  if (!file.exists(micro_file)) return(list(key = config_key, status = "SKIP no micro"))
  if (!file.exists(flags_file)) return(list(key = config_key, status = "SKIP no pole flags"))
  existing <- tryCatch(fromJSON(json_path, simplifyVector = FALSE), error = function(e) NULL)
  if (is.null(existing)) return(list(key = config_key, status = "SKIP unreadable"))

  t0 <- proc.time()
  df <- fread(micro_file)
  df[, stay_home   := ifelse(response == "yes", 1L, 0L)]
  df[, infection_pct := as.numeric(infection_level)]
  df <- merge(df, agents, by = "agent_id", all.x = TRUE)
  df[, male          := ifelse(gender == "male", 1L, 0L)]
  df[, extraverted   := ifelse(grepl("extroverted", traits), 1L, 0L)]
  df[, agreeable     := ifelse(grepl("\\bagreeable\\b", traits), 1L, 0L)]
  df[, conscientious := ifelse(grepl("unconscientious", traits), 0L, 1L)]
  df[, emot_stable   := ifelse(grepl("emotionally stable", traits), 1L, 0L)]
  df[, open_to_exp   := ifelse(grepl("open to experience", traits), 1L, 0L)]
  df[, age_years     := as.integer(age)]

  flags <- fread(flags_file)
  df3 <- merge(df, flags, by = c("agent_id", "rep", "infection_level"), all.x = TRUE)
  all_mention_cols <- c(paste0("mentioned_", POLE_NAMES), "mentioned_infection", "mentioned_age")
  for (fc in all_mention_cols) if (fc %in% names(df3)) df3[is.na(get(fc)), (fc) := 0L]

  # ── Per-pole contrast check ─────────────────────────────────
  pole_flags <- list()
  included_main <- c()
  included_interactions <- c()
  for (pole in POLE_NAMES) {
    fc <- paste0("mentioned_", pole)
    rate <- mean(df3[[fc]], na.rm = TRUE)
    sufficient <- isTRUE(rate >= threshold && rate <= (1 - threshold))
    pole_flags[[pole]] <- list(mention_rate = round(rate, 4), sufficient = sufficient,
                               paired_trait = POLE_TO_TRAIT[[pole]])
    if (sufficient) {
      included_main <- c(included_main, fc)
      included_interactions <- c(included_interactions, paste0(POLE_TO_TRAIT[[pole]], ":", fc))
    }
  }
  # Context (infection + age)
  context_flags_info <- list()
  for (ctx in names(CONTEXT_FLAGS)) {
    fc <- paste0("mentioned_", ctx)
    rate <- mean(df3[[fc]], na.rm = TRUE)
    sufficient <- isTRUE(rate >= threshold && rate <= (1 - threshold))
    context_flags_info[[ctx]] <- list(mention_rate = round(rate, 4), sufficient = sufficient,
                                       paired = CONTEXT_FLAGS[[ctx]])
    if (sufficient) {
      included_main <- c(included_main, fc)
      included_interactions <- c(included_interactions, paste0(CONTEXT_FLAGS[[ctx]], ":", fc))
    }
  }

  base_terms <- c("infection_pct", "I(infection_pct^2)",
                  "male", "extraverted", "agreeable", "conscientious",
                  "emot_stable", "open_to_exp", "age_years")
  all_terms <- c(base_terms, included_main, included_interactions)
  formula_str <- paste("stay_home ~", paste(all_terms, collapse = " + "), "+ (1 | agent_id)")
  m3_formula <- as.formula(formula_str)

  excluded <- setdiff(c(paste0("mentioned_", POLE_NAMES), paste0("mentioned_", names(CONTEXT_FLAGS))), included_main)
  cat(sprintf("[%s] %d main + %d interaction  (excluded: %s)\n",
              config_key, length(included_main), length(included_interactions),
              if (length(excluded) > 0) paste(excluded, collapse = ", ") else "none"))

  t_fit <- proc.time()
  m3 <- tryCatch(
    glmer(m3_formula, family = binomial, data = df3,
          control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))),
    error = function(e) e
  )
  fit_secs <- round((proc.time() - t_fit)["elapsed"], 1)
  if (inherits(m3, "error")) {
    return(list(key = config_key, status = paste("ERROR:", conditionMessage(m3)), fit_s = fit_secs))
  }

  coef_table <- summary(m3)$coefficients
  m3_coefs <- extract_coefs(coef_table)
  if ("age_years" %in% names(m3_coefs)) { m3_coefs$age <- m3_coefs$age_years; m3_coefs$age_years <- NULL }
  re_var <- as.data.frame(VarCorr(m3))$vcov[1]
  conv_warn <- NULL
  if (length(m3@optinfo$conv$lme4$messages) > 0) conv_warn <- paste(m3@optinfo$conv$lme4$messages, collapse = "; ")

  # DHARMa
  t_dh <- proc.time()
  sim3 <- tryCatch(DHARMa::simulateResiduals(fittedModel = m3, n = 250, plot = FALSE, seed = 42),
                    error = function(e) NULL)
  dharma_info <- tryCatch({
    if (is.null(sim3)) stop("simulateResiduals failed")
    resids <- sim3$scaledResiduals
    probs <- seq(0.01, 0.99, by = 0.01)
    qvals <- as.numeric(quantile(resids, probs = probs, na.rm = TRUE))
    t_unif <- DHARMa::testUniformity(sim3, plot = FALSE)
    t_disp <- DHARMa::testDispersion(sim3, plot = FALSE)
    list(n_sim = 250L, n_obs = length(resids), probs = probs, quantiles = qvals,
         ks_statistic = as.numeric(t_unif$statistic), ks_p_value = as.numeric(t_unif$p.value),
         dispersion_ratio = as.numeric(t_disp$statistic), dispersion_p = as.numeric(t_disp$p.value))
  }, error = function(e) list(error = e$message))
  dh_secs <- round((proc.time() - t_dh)["elapsed"], 1)

  # BLUPs
  blups_m3 <- tryCatch({
    re <- ranef(m3)$agent_id
    list(agent_ids = rownames(re), intercepts = round(as.numeric(re[[1]]), 6),
         sd_estimated = round(as.data.frame(VarCorr(m3))$sdcor[1], 6))
  }, error = function(e) NULL)

  # Calibration bins
  calib_m3 <- tryCatch({
    preds <- as.numeric(predict(m3, type = "response"))
    df_tmp <- data.table(p = preds, y = df3$stay_home, inf = df3$infection_pct)
    df_tmp[, .(predicted = mean(p, na.rm = TRUE), observed = mean(y, na.rm = TRUE),
               n = .N), by = inf][order(inf)]
  }, error = function(e) NULL)
  calib_by_age_m3 <- tryCatch({
    preds <- as.numeric(predict(m3, type = "response"))
    df_tmp <- data.table(p = preds, y = df3$stay_home, age = df3$age_years)
    df_tmp[, age_bin := floor((age - 18) / 5)]
    df_tmp[, .(age_min = min(age), age_max = max(age), age_mid = mean(age),
               predicted = mean(p, na.rm = TRUE), observed = mean(y, na.rm = TRUE),
               n = .N), by = age_bin][order(age_bin)]
  }, error = function(e) NULL)

  # Residuals by infection/age (DHARMa scaled)
  resids_by_inf <- tryCatch({
    if (!is.null(sim3)) {
      df_tmp <- data.table(r = sim3$scaledResiduals, inf = df3$infection_pct)
      df_tmp[, .(mean_resid = mean(r, na.rm = TRUE), sd_resid = sd(r, na.rm = TRUE),
                 n = .N), by = inf][order(inf)]
    } else NULL
  }, error = function(e) NULL)
  resids_by_age <- tryCatch({
    if (!is.null(sim3)) {
      df_tmp <- data.table(r = sim3$scaledResiduals, age = df3$age_years)
      df_tmp[, age_bin := floor((age - 18) / 5)]
      df_tmp[, .(age_min = min(age), age_max = max(age), age_mid = mean(age),
                 mean_resid = mean(r, na.rm = TRUE), sd_resid = sd(r, na.rm = TRUE),
                 n = .N), by = age_bin][order(age_bin)]
    } else NULL
  }, error = function(e) NULL)

  # BLUPs vs predictors
  blups_vs_preds <- tryCatch({
    if (!is.null(blups_m3)) {
      agent_data <- unique(df3[, .(agent_id, male, extraverted, agreeable,
                                    conscientious, emot_stable, open_to_exp, age_years)])
      blup_dt <- data.table(agent_id = as.character(blups_m3$agent_ids), blup = blups_m3$intercepts)
      agent_data[, agent_id := as.character(agent_id)]
      merged <- merge(blup_dt, agent_data, by = "agent_id", all.x = TRUE)
      dummy_assoc <- function(y, x) {
        y1 <- y[x == 1]; y0 <- y[x == 0]
        if (length(y1) < 2 || length(y0) < 2) return(list(estimate = NA, se = NA))
        list(estimate = as.numeric(mean(y1, na.rm = TRUE) - mean(y0, na.rm = TRUE)),
             se = as.numeric(sqrt(var(y1, na.rm = TRUE)/length(y1) + var(y0, na.rm = TRUE)/length(y0))))
      }
      cont_assoc <- function(y, x) {
        if (length(x) < 3 || var(x, na.rm = TRUE) == 0) return(list(estimate = NA, se = NA))
        fit <- tryCatch(lm(y ~ x), error = function(e) NULL)
        if (is.null(fit)) return(list(estimate = NA, se = NA))
        sl <- as.numeric(coef(fit)[2]); sl_se <- as.numeric(summary(fit)$coefficients[2,2])
        xr <- max(x, na.rm = TRUE) - min(x, na.rm = TRUE)
        list(estimate = sl * xr, se = sl_se * xr)
      }
      list(
        age          = c(cont_assoc(merged$blup, merged$age_years), list(type = "continuous")),
        male         = c(dummy_assoc(merged$blup, merged$male),        list(type = "dummy")),
        extraverted  = c(dummy_assoc(merged$blup, merged$extraverted), list(type = "dummy")),
        agreeable    = c(dummy_assoc(merged$blup, merged$agreeable),   list(type = "dummy")),
        conscientious= c(dummy_assoc(merged$blup, merged$conscientious), list(type = "dummy")),
        emot_stable  = c(dummy_assoc(merged$blup, merged$emot_stable), list(type = "dummy")),
        open_to_exp  = c(dummy_assoc(merged$blup, merged$open_to_exp), list(type = "dummy"))
      )
    } else NULL
  }, error = function(e) NULL)

  total_secs <- round((proc.time() - t0)["elapsed"], 1)

  existing$model3 <- list(
    type           = "mention_interaction_logit_pole",
    formula        = formula_str,
    coefficients   = m3_coefs,
    pole_flags     = pole_flags,
    context_flags  = context_flags_info,
    n_interactions = length(included_interactions),
    n_mention_main = length(included_main),
    threshold      = threshold,
    fit = list(aic = round(AIC(m3), 2), bic = round(BIC(m3), 2),
               n = nrow(df3), n_groups = length(unique(df3$agent_id)),
               re_variance = round(re_var, 6)),
    warning = conv_warn, dharma = dharma_info, blups = blups_m3,
    calibration_bins   = if (!is.null(calib_m3)) as.list(as.data.frame(calib_m3)) else NULL,
    calibration_by_age = if (!is.null(calib_by_age_m3)) as.list(as.data.frame(calib_by_age_m3)) else NULL,
    resids_by_infection = if (!is.null(resids_by_inf)) as.list(as.data.frame(resids_by_inf)) else NULL,
    resids_by_age      = if (!is.null(resids_by_age)) as.list(as.data.frame(resids_by_age)) else NULL,
    blups_vs_predictors = blups_vs_preds
  )
  write_json(existing, json_path, auto_unbox = TRUE, digits = 8, pretty = TRUE)

  disp <- if (!is.null(dharma_info$dispersion_ratio)) sprintf("disp=%.2f", dharma_info$dispersion_ratio) else "disp=?"
  max_se <- if (length(m3_coefs) > 0) {
    max(sapply(m3_coefs, function(c) if (is.list(c)) c$se else NA), na.rm = TRUE)
  } else NA
  list(key = config_key,
       status = sprintf("OK %s · max SE=%.2f · fit %.1fs · dh %.1fs · total %.1fs",
                       disp, max_se, fit_secs, dh_secs, total_secs))
}

t_run <- proc.time()
if (n_cores > 1) {
  results <- mclapply(json_files, process_one, mc.cores = n_cores)
} else {
  results <- lapply(json_files, function(f) {
    r <- process_one(f)
    cat(sprintf("  %-55s %s\n", r$key, r$status))
    r
  })
}
wall <- (proc.time() - t_run)["elapsed"]
cat(sprintf("\nWall time: %.1fs\n", wall))
if (n_cores > 1) {
  for (r in results) cat(sprintf("  %-55s %s\n", r$key, r$status))
}
